(function ensightenInit(){var ensightenOptions = {client: "capitalone", clientId: 581, publishPath: "prod", isPublic:1, serverComponentLocation: "nexus.ensighten.com/capitalone/prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/capitalone/prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "true", registryNs : "ensBootstraps", generatedOn : "Mon Jun 03 21:24:01 GMT 2019", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function l(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function m(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function n(){for(var a=b.dataDefinitionIds.length,c=!0,d=0;d<a;d++){var e=b.dataDefinitions[b.dataDefinitionIds[d]];if(!e||
null==e.endRegistration){c=!1;break}}c&&b.callOnDataDefintionComplete()}var e={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};e.version="1.26.0";e.nexus=f.nexus||"nexus.ensighten.com";e.rand=-1;e.currSec=(new Date).getSeconds();e.options={interval:f.interval||100,erLoc:f.errorLocation||e.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||e.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||e.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||e.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};e.ruleList=[];e.allDeploymentIds=[];e.runDeploymentIds=[];e.runRuleIds=[];e.exceptionList=[];e.ensightenVariables={};e.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var c=0;c<a.dependencies.length;c++)if(!1===a.dependencies[c]())return;
a.execute()}};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;e.DependencyNotAvailableException=l;m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;e.BeaconException=m;e.checkForInvalidDependencies=function(a,c,d,h){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new e.DependencyNotAvailableException(h[a])),c&&-1!==c&&e.allDeploymentIds.push(c),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var c=(e.currSec||0)%20,b=e.options.beaconSamplingSeedValue;-1===b?a=!0:0!==c&&0===b%c&&(a=!0)}catch(h){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+e.options.scLoc,!1,a||!0,e.options.scUseCacheBuster)};b.setVariable=function(a,c){e.ensightenVariables[a]=
c};b.getVariable=function(a){return a in e.ensightenVariables?e.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<e.ruleList.length;a++)e.test(e.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();e.exceptionList.push(a);a=window.location.protocol+"//"+e.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(e.options.clientId||-1)+"&client="+encodeURIComponent(e.options.client||"")+"&publishPath="+encodeURIComponent(e.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(c){window[ensightenOptions.ns].reportException(c)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(e.runDeploymentIds.push(this.deploymentId),e.runRuleIds.push(this.id)),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;e.ruleList.push(a);
-1!==a.deploymentId&&e.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var c=0;c<e.ruleList.length;c++)if(e.ruleList[c].id===a)return e.ruleList[c];return!1};b.getRuleList=function(){return e.ruleList};b.clearRuleList=function(){e.ruleList=[]};b.getAllDeploymentIds=function(){return e.allDeploymentIds};b.getRunRuleIds=function(){return e.runRuleIds};b.getRunDeploymentIds=function(){return e.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:
!1};e.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};b.Alert=function(a){var c=new Date;c=c.getFullYear()+"-"+e.toTwoChar(c.getMonth())+"-"+e.toTwoChar(c.getDate())+" "+e.toTwoChar(c.getHours())+":"+e.toTwoChar(c.getMinutes())+":"+e.toTwoChar(c.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(c);this.subject=encodeURIComponent(this.subject);
this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+e.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+e.options.clientId+"&client="+e.options.client+"&publishPath="+e.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var c=new Image(0,0);c.src=a;return c};b.insertScript=function(a,c,d,h){var p=
document.getElementsByTagName("script"),g;h=void 0!==h?h:!0;if(void 0!==c?c:1)for(g=0;g<p.length;g++)if(p[g].src===a&&p[g].readyState&&/loaded|complete/.test(p[g].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;e.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));c=window.location.href;"object"===typeof d&&d.PageID&&(c=d.PageID,delete d.PageID);if("object"===typeof d)for(g in d){g=~c.indexOf("#")?c.slice(c.indexOf("#"),c.length):"";c=c.slice(0,g.length?c.length-g.length:
c.length);c+=~c.indexOf("?")?"&":"?";for(k in d)c+=k+"="+d[k]+"&";c=c.slice(0,-1)+g;break}a+="?";h&&(a+="r="+e.rand+"&");a+="ClientID="+encodeURIComponent(e.options.clientId)+"&PageID="+encodeURIComponent(c)}(function(a,c,b){var d=c.head||c.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=c.createElement("script");a.src=b;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,
d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,c,b){var d=document.getElementsByTagName("script"),e;b=d[0];for(e=0;e<d.length;e++)if(d[e].src===a&&d[e].readyState&&/loaded|complete/.test(d[e].readyState))try{c()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;d.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.onload=d.onreadystatechange=function(){if(!this.readyState||
"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{c.call(this)}catch(g){window[ensightenOptions.ns].reportException(g)}}};b.parentNode.insertBefore(d,b)};b.insertPageFiles=function(a){var b=0,d=0,e=function(){d==a.length-1&&window[ensightenOptions.ns].callOnPageSpecificCompletion();d++};for(b=0;b<a.length;++b)window[ensightenOptions.ns].loadScriptCallback(a[b],e)};b.unobtrusiveAddEvent=function(a,
b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(p){window[ensightenOptions.ns].reportException(p)}};b.anonymous=function(a,c){return function(){try{b.currentRuleId=c?c:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,
deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var c,d=0;d<a.length;++d)if(c=b.getRule(parseInt(a[d],10)),!c||!c.executionData.hasRun)return!1;return!0};
b.bindDependencyImmediate=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});
if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,
c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,c,d,f,p){var g=[];if(!e.checkForInvalidDependencies(c,f,d,p)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:f||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var c=a?a.length:0,d=0;d<c;d++){var e=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(e)&&b.dataDefinitionIds.push(e);else{for(var f=!1,g=
b.dataDefinitionIds.length,l=0;l<g;l++)if(b.dataDefinitionIds[l]===e){f=!0;break}f||b.dataDefinitionIds.push(e)}}b.pageSpecificDataDefinitionsSet=!0;n()};b.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,c){var d=b.dataDefinitions[c];d||(d=new b.DataDefinition(c,
a),b.dataDefinitions[c]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());b.pageSpecificDataDefinitionsSet&&n()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=
!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=
function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var r=function(){var a=[],b=!1,d=!1;return{add:function(c){b&&!d?c():"function"==typeof c&&(a[a.length]=
c)},exec:function(){d=!0;do{var c=a;a=[];b=!0;for(var e=0;e<c.length;e++)try{c[e].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);d=!1},haveRun:function(){return b}}};b.new_fArray=function(){return r()};e.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var d=log4javascript.getDefaultLogger();b.log=a(d.info,d);b.debug=a(d.debug,d);b.info=
a(d.info,d);b.warn=a(d.warn,d);b.error=a(d.error,d)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?e.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(e.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,
!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(c){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===document.readyState&&(b.executionState.DOMParsed=!0,b.executionState.DOMLoaded=!0);"true"===e.options.enableTagAuditBeacon&&b.sampleBeacon()&&
window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],c,d,h,l,g=0;g<e.ruleList.length;++g)d=e.ruleList[g],h=d.executionData.hasRun?"1":"0",l=d.deploymentId.toString()+"|"+d.id.toString()+"|"+h,a.push(l);c="["+a.join(";")+"]";var m=window.location.protocol+"//"+e.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+c+"&idx=0&r="+e.rand;b.imageRequest(m)}catch(q){b.currentRuleId=
-1,b.currentDeploymentId=-1,a=new e.BeaconException(q),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,e.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){f=f.timing||{};var l=f.navigationStart||0,m={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var n="&ns="+encodeURIComponent(f.navigationStart);for(var e in m)if(void 0!==f[e]){var b=f[e]-l;n+="&"+m[e]+"="+(0<b?encodeURIComponent(b):0)}else n+="&"+m[e]+"=-1";window[ensightenOptions.ns].timing=n;e=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";n=f.indexOf("/",0);l=f.indexOf("/code/");f=f.substring(n,l)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+e+f)}}});
	
    /*
     MIT License (c) copyright 2013 original author or authors */
    window[ensightenOptions.ns].data||(window[ensightenOptions.ns].when=function(){function f(a,b,d,c){return l(a).then(b,d,c)}function p(a){this.then=a}function l(a){return c(function(b){b(a)})}function c(b){function g(a){k&&(r=e(a),d(k,r),k=u)}function f(a){g(h(a))}function q(b){k&&d(k,a(b))}var r,k=[];try{b(g,f,q)}catch(E){f(E)}return new p(function(a,b,d){return c(function(c,g,e){k?k.push(function(f){f.then(a,b,d).then(c,g,e)}):n(function(){r.then(a,b,d).then(c,g,e)})})})}function e(a){return a instanceof
    p?a:a!==Object(a)?m(a):c(function(b,d,c){n(function(){try{var g=a.then;"function"===typeof g?z(g,a,b,d,c):b(m(a))}catch(y){d(y)}})})}function m(a){var b=new p(function(d){try{return"function"==typeof d?e(d(a)):b}catch(D){return h(D)}});return b}function h(a){var b=new p(function(d,c){try{return"function"==typeof c?e(c(a)):b}catch(F){return h(F)}});return b}function a(b){var d=new p(function(c,g,e){try{return"function"==typeof e?a(e(b)):d}catch(y){return a(y)}});return d}function d(a,b){n(function(){for(var d,
    c=0;d=a[c++];)d(b)})}function b(a,b,d,g,e){q(2,arguments);return f(a,function(a){return c(function(d,c,g){function e(a){h(a)}function q(a){u(a)}var k;var n=a.length>>>0;var t=Math.max(0,Math.min(b,n));var w=[];var x=n-t+1;var m=[];if(t){var h=function(a){m.push(a);--x||(u=h=r,c(m))};var u=function(a){w.push(a);--t||(u=h=r,d(w))};for(k=0;k<n;++k)k in a&&f(a[k],q,e,g)}else d(w)}).then(d,g,e)})}function t(a,b,d,c){q(1,arguments);return k(a,w).then(b,d,c)}function k(a,b){return f(a,function(a){return c(function(d,
    c,g){var e,q;var k=e=a.length>>>0;var r=[];if(k){var n=function(a,e){f(a,b).then(function(a){r[e]=a;--k||d(r)},c,g)};for(q=0;q<e;q++)q in a?n(a[q],q):--k}else d(r)})})}function n(a){1===x.push(a)&&A(g)}function g(){for(var a,b=0;a=x[b++];)a();x=[]}function q(a,b){for(var d,c=b.length;c>a;)if(d=b[--c],null!=d&&"function"!=typeof d)throw Error("arg "+c+" must be a function");}function r(){}function w(a){return a}f.defer=function(){var a,b;var d={promise:u,resolve:u,reject:u,notify:u,resolver:{resolve:u,
    reject:u,notify:u}};d.promise=a=c(function(c,g,e){d.resolve=d.resolver.resolve=function(d){if(b)return l(d);b=!0;c(d);return a};d.reject=d.resolver.reject=function(d){if(b)return l(h(d));b=!0;g(d);return a};d.notify=d.resolver.notify=function(a){e(a);return a}});return d};f.resolve=l;f.reject=function(a){return f(a,h)};f.join=function(){return k(arguments,w)};f.all=t;f.map=k;f.reduce=function(a,b){var d=z(B,arguments,1);return f(a,function(a){var c=a.length;d[0]=function(a,d,g){return f(a,function(a){return f(d,
    function(d){return b(a,d,g,c)})})};return G.apply(a,d)})};f.any=function(a,d,c,g){return b(a,1,function(a){return d?d(a[0]):a[0]},c,g)};f.some=b;f.isPromise=function(a){return a&&"function"===typeof a.then};p.prototype={otherwise:function(a){return this.then(u,a)},ensure:function(a){function b(){return l(a())}return this.then(b,b).yield(this)},yield:function(a){return this.then(function(){return a})},spread:function(a){return this.then(function(b){return t(b,function(b){return a.apply(u,b)})})},always:function(a,
    b){return this.then(a,a,b)}};var u;var x=[];var H=setTimeout;var A="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(a){H(a,0)};var v=Function.prototype;var C=v.call;var z=v.bind?C.bind(C):function(a,b){return a.apply(b,B.call(arguments,2))};v=[];var B=v.slice;var G=v.reduce||function(a){var b=0;var d=Object(this);var c=d.length>>>0;var g=arguments;if(1>=g.length)for(;;){if(b in
    d){g=d[b++];break}if(++b>=c)throw new TypeError;}else g=g[1];for(;b<c;++b)b in d&&(g=a(g,d[b],b,d));return g};return f}(),function(){function f(c,f){return l.all(f||[],function(e){return c.apply(null,e)})}function p(e){var m=c.call(arguments,1);return function(){return f(e,m.concat(c.call(arguments)))}}var l=window[ensightenOptions.ns].when;var c=[].slice;l.apply=f;l.call=function(e){return f(e,c.call(arguments,1))};l.lift=p;l.bind=p;l.compose=function(e){var m=c.call(arguments,1);return function(){var h=
    c.call(arguments);h=f(e,h);return l.reduce(m,function(a,d){return d(a)},h)}}}(),window[ensightenOptions.ns].data=function(f,p){function l(a,d){this.name="DataDefinitionException";this.message=d||"Data definitions cannot be resolved as there are invalid id(s): "+a}var c={engines:{memory:{get:function(a){if(e.utils.isArray(a)){for(var d=[],b=0;b<a.length;b++)d.push(c.data[a[b]]);return f[ensightenOptions.ns].when.resolve(d)}d=c.dataDefinitions[a]||{storage:{get:function(){}}};d=d.storage.get(d);c.data[a]=
    d;return f[ensightenOptions.ns].when.resolve(c.data[a])},set:function(a,d){if(e.utils.isArray(a))for(var b in a)c.data[a[b]]=d[b];else c.data[a]=d;return f[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(e.utils.isArray(a))for(var d in a)delete c.data[a[d]];else delete c.data[a];return f[ensightenOptions.ns].when.resolve(!0)},clear:function(a){c.data={};c.definitions={};return f[ensightenOptions.ns].when.resolve(!0)},all:function(){return f[ensightenOptions.ns].when.resolve(c.data)}}},
    normalizeInputArgs:function(a,d){var b={key:[],val:p},c;if(e.utils.isPlainObject(a))for(c in b.val=[],a)b.key.push(c),b.val.push(a[c]);else e.utils.isArray(a),b.key=a,b.val=d;return b},definitions:{},data:{}},e={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(d){return a}}}},m=function(){return f[ensightenOptions.ns].when.reject("Not Implemented.")};
    l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;c.DataDefinitionException=l;c.checkForInvalidDataDefinitions=function(a){e.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(f[ensightenOptions.ns].reportException(new c.DataDefinitionException(a)),!0):!1};c.collectAvailableDataDefinitions=function(a){for(var d=[],b=0;b<a.length;b++){var t=parseInt(a[b],10),k=f[ensightenOptions.ns].dataDefinitions[t];if(null===k||k===p)if(k=e.storage.session.get({id:t}),
    null!==k&&k!==p)e.set(t,k),c.dataDefinitions[t]={id:t,load:"visitor",storage:e.storage.visitor,missingDDFromCache:!0},d.push(f[ensightenOptions.ns].data.get(""+t));else return f[ensightenOptions.ns].reportException(new c.DataDefinitionException(a,"Invalid data definition used: "+t)),{promises:[],isInvalid:!0};else d.push(f[ensightenOptions.ns].data.get(""+a[b]))}return{promises:d,isInvalid:!1}};c.getSync=function(a){function d(a){var d=a.extract||t,c=a.transform||k,g=!1,e=null,f=null;try{e=d()}catch(v){e=
    null,g=!0}try{f=c(e)}catch(v){f=null,g=!0}g&&b.push(a.id);return f}var b=[],t=function(){return document},k=function(a){return null!==a&&a!==p?a.toString():null},n=parseInt(a);a="string"===typeof a?a.split("."):[];var g={},q="";if(!isNaN(n)&&"undefined"===typeof c.dataDefinitions[n])return f[ensightenOptions.ns].reportException(new c.DataDefinitionException(n,"Error resolving data definition: "+n+".  Does not exist on the page.")),"Data definition specified does not exist on the page";if(isNaN(n)&&
    "undefined"===typeof c.dataDefinitionsBySourceCollName[""+a[0]+"."+a[1]+"."+a[2]])return f[ensightenOptions.ns].reportException(new c.DataDefinitionException(a,"Error resolving data definition: "+a[0]+"."+a[1]+"."+a[2]+".  Does not exist on the page.")),"Data definition specified does not exist on the page";isNaN(n)?3==a.length&&(g=e.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2])):g=e.getDataDefinitionById(n);q=g.load&&g.load.match(/(session|visitor)/i)&&g.storage&&g.storage.get?g.storage.get(g):
    d(g);0<b.length&&f[ensightenOptions.ns].reportException(new c.DataDefinitionException(b,"Error resolving data definitions synchronously: "+b));return q};c.dataDefinitions={};c.dataDefinitionsBySourceCollName={};e.defineEngine=function(a,d){var b,e=["get","set","remove","clear","all"];c.engines[a]=d;if(!d.returnsPromise)for(b=0;b<e.length;b++){var k=e[b];d[k]=f[ensightenOptions.ns].when.lift(d[k])}};e.storage={instance:{set:function(a,d){},get:function(a){return c.getSync(a.id)}},page:{set:function(a,
    d){},get:function(a){return c.data[a.id]}},session:{set:function(a,d){var b=e.storage.session.get({id:a}),c=new Date,k=c.getTime();c.setTime(k+18E5);null!=b&&(d=b);f[ensightenOptions.ns].data.cookie.utils.set(a,d,{expires:c.toGMTString()});b={expires:c.getTime(),value:d};f[ensightenOptions.ns].data.local.utils.set(a,b)},get:function(a){var d=f[ensightenOptions.ns].data.cookie.utils.get(a.id),b=f.JSON&&f.JSON.stringify?f.JSON:f[ensightenOptions.ns].JSON;b=b||{};var c=new Date;c=c.getTime();if(null===
    d){try{var e=b.parse(f[ensightenOptions.ns].data.local.utils.get(a.id))}catch(n){e=null}null!=e&&(e.expires=+e.expires,c<=e.expires?d=e.value:""==e.expires&&e.value!=p?d=e.value:f[ensightenOptions.ns].data.local.utils.remove(a.id))}return d}},visitor:{set:function(a,d){var b=e.storage.session.get({id:a});null!=b&&(d=b);f[ensightenOptions.ns].data.cookie.utils.set(a,d);f[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:d})},get:function(a){return e.storage.session.get(a)}}};e.getEngine=
    e.engine=function(a){return a?c.engines[a]||{get:m,set:m,remove:m,clear:m,all:m}:c.engines};e.all=function(a){return f[ensightenOptions.ns].data.engine(a||"memory").all()};e.get=function(a,d,b){d=d||"memory";b=b||{};-1<a.indexOf(",")?(a=a.split(","),a=c.normalizeInputArgs(a)):a=c.normalizeInputArgs(a);return b.wait?c.getWait(a.key,f[ensightenOptions.ns].data.engine(d),b):c.data&&c.data.hasOwnProperty(a.key)?f[ensightenOptions.ns].data.engine(d).get(a.key):c.getWaitForKey(a.key,f[ensightenOptions.ns].data.engine(d),
    b)};c.getWait=function(a,d,b){var c=+new Date,k=f[ensightenOptions.ns].when.defer(),n=function(){var c=d.get(a);if(-1===b.wait)return c;c.then(function(a){b.setCheck(a)?k.resolve(a):setTimeout(g,b.interval)},function(a){setTimeout(g,b.interval)})},g=function(){var a=+new Date-c;-1!==b.wait&&a<b.wait?n():k.reject("Timeout")};b.interval=b.interval||500;b.wait=b.wait||5E3;e.utils.isArray(a)?b.setCheck=b.setCheck||function(a){for(var b=!0,d=0;d<a.length;d++)b=b&&!!a[d];return b}:b.setCheck=b.setCheck||
    function(a){return!!a};n();return k.promise};c.getWaitForKey=function(a,d,b){var e=f[ensightenOptions.ns].when.defer(),k=function(){if(c.data&&c.data.hasOwnProperty(a)){var g=d.get(a);if(-1===b.wait)return g;g.then(function(a){e.resolve(a)},function(a){e.reject(a)})}else setTimeout(n,b.interval)},n=function(){k()};b.interval=b.interval||100;b.wait=b.wait||1;k();return e.promise};e.set=function(a,d,b){var e=c.normalizeInputArgs(a,d);Array.prototype.slice.call(arguments);return f[ensightenOptions.ns].data.engine(b||
    "memory").set(e.key,e.val)};e.remove=function(a,d){return f[ensightenOptions.ns].data.engine(d||"memory").remove(a)};e.clear=function(a){return f[ensightenOptions.ns].data.engine(a||"memory").clear()};e.define=function(a,d){d&&(a.name=d.id||d.name);if(!a.name)return f[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));a.id=a.name;var b=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return f[ensightenOptions.ns].when.resolve()};
    a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=f[ensightenOptions.ns].data.engine("memory");a.storage=e.storage[b.toLowerCase()]||e.storage.page;var h=a.extract||function(){return document},k=a.transform||function(a){return a},n=function(b,d){var c=[];c.push(a.persist.set(b,d));a.storage.set(a.id,d);"object"==typeof f[ensightenOptions.ns].data.dataExport&&f[ensightenOptions.ns].data.dataExport(b,d,a.collection);f[ensightenOptions.ns].when.all(c).then(function(a){g.resolve(a)},
    function(a){g.reject(a)})},g=f[ensightenOptions.ns].when.defer();try{var q=a.trigger()}catch(r){f[ensightenOptions.ns].reportException(new c.DataDefinitionException(null,'"'+r+'" error caught in Data Definition trigger: '+a.dataDefName+", ID:"+a.id+". Using bottom of body trigger.")),q=f[ensightenOptions.ns].data.bottomOfBodyTrigger()}q.then(function(){g.resolve(f[ensightenOptions.ns].when.reduce([function(){try{return h()}catch(r){return f[ensightenOptions.ns].reportException(new c.DataDefinitionException(null,
    '"'+r+'" error caught in Data Definition extractor: '+a.dataDefName+", ID:"+a.id+".")),null}}(),function(){try{return k.apply(this,arguments)}catch(r){return f[ensightenOptions.ns].reportException(new c.DataDefinitionException(null,'"'+r+'" error caught in Data Definition transformer: '+a.dataDefName+", ID "+a.id+".")),null}},n],function(b,d,c,e){if(1==c)return d(b);2==c&&d(a.name,b)}))},function(a){g.reject(a)});c.dataDefinitions[a.id]=a;c.dataDefinitionsBySourceCollName[""+a.source+"."+a.collection+
    "."+a.dataDefName]=a;return g.promise};e.checkConditions=function(a){var d,b={lt:function(a,b){var d=+a,e=+b;return isNaN(d)||isNaN(e)?(f[ensightenOptions.ns].reportException(new c.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+b)),!1):d<e},gt:function(a,b){var d=+a,e=+b;return isNaN(d)||isNaN(e)?(f[ensightenOptions.ns].reportException(new c.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+
    b)),!1):d>e},eql:function(a,b){return a==b},exists:function(a,b){return null==a||a==p||""==a?!1:!0},re:function(a,b,d){b=new RegExp(b,d?"i":"");try{return a.match(b)}catch(q){return!1}},starts:function(a,d,c){d=e.utils.escapeRegEx(d);return b.re(a,"^"+d,c)},ends:function(a,d,c){d=e.utils.escapeRegEx(d);return b.re(a,d+"$",c)},contains:function(a,d,c){d=e.utils.escapeRegEx(d);return b.re(a,".*"+d+".*",c)}};b.is=b.eql;b["starts with"]=b.starts;b["ends with"]=b.ends;b["is greater than"]=b.gt;b["is less than"]=
    b.lt;b.matches=b.re;for(d=0;d<a.values.length;d++){var h=(a.customComparator?a.customComparator[d]?a.customComparator[d]:b[a.comparators[d]]:b[a.comparators[d]])(a.values[d],a.compareTo[d],a.caseInsensitive?a.caseInsensitive[d]||!1:!1);a.not[d]&&(h=!h);if(!h)return!1}return!0};e.triggerPromise=function(a,d,b){b=b||5E3;var c=+new Date,e=f[ensightenOptions.ns].when.defer();(function(){var f=a();f!=d?e.resolve(f):+new Date-c<b?setTimeout(arguments.callee,200):e.reject("timed out")})();return e.promise};
    e.timeoutPromise=function(a,d){var b=f[ensightenOptions.ns].when.defer();d=d||800;a.then(b.resolve,b.reject);setTimeout(function(){b.reject(Error("timed out"))},d);return b.promise};e.delayTrigger=function(a){a=a||10;var d=f[ensightenOptions.ns].when.defer();setTimeout(function(){d.resolve()},a);return d.promise};e.delayUntilTrigger=function(a,d,b,c){b=b||null;c=c||200;var e=+new Date,h=f[ensightenOptions.ns].when.defer();(function(){var g=a();g!=d?h.resolve(g):b?+new Date-e<b?setTimeout(arguments.callee,
    c):h.reject("timed out"):setTimeout(arguments.callee,c)})();return h.promise};c.applyTrigger=function(a){var d=f[ensightenOptions.ns].when.defer();a(function(){d.resolve(!0)});return d.promise};e.immediateTrigger=function(){return c.applyTrigger(f[ensightenOptions.ns].bindImmediate)};e.bottomOfBodyTrigger=function(){return c.applyTrigger(f[ensightenOptions.ns].bindDOMParsed)};e.whenValueExistsTrigger=function(){return f[ensightenOptions.ns].when.resolve(this.extract())};e.afterEnsightenCompleteTrigger=
    function(){return c.applyTrigger(f[ensightenOptions.ns].bindPageSpecificCompletion)};e.afterElementsDownloadedTrigger=function(){return c.applyTrigger(f[ensightenOptions.ns].bindDOMLoaded)};e.getAllDataDefinitionsOnCurrentPage=function(){return c.dataDefinitions};e.getAllDataDefinitionsOnCurrentPage_S_C_N=function(){return c.dataDefinitionsBySourceCollName};e.getDataDefinitionById=function(a){return c.dataDefinitions[a||-1]||{}};e.getDataDefinitionBySourceCollectionName=function(a,d,b){return c.dataDefinitionsBySourceCollName[""+
    a+"."+d+"."+b]||{}};e.getDataDefinitionByPercentSyntax=function(a){a=(""+a).split("_");return 1>a.length?{}:c.dataDefinitions[a[1]]||{}};e.resolve=function(a,d){var b=this,h=null;if(!c.checkForInvalidDataDefinitions(a))if(d)f[ensightenOptions.ns].bindDataDefinitionComplete(function(){var e=c.collectAvailableDataDefinitions(a);e.isInvalid||f[ensightenOptions.ns].when.all(e.promises).then(function(e){try{d.apply(b,e)}catch(r){f[ensightenOptions.ns].reportException(new c.DataDefinitionException(a,"Error resolving data definitions: "+
    a+". Details: "+r))}},function(b){f[ensightenOptions.ns].reportException(new c.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+b))})});else{h=[];var k=a;e.utils.isArray(a)||(k=[a]);for(var m=0;m<k.length;m++)h.push(c.getSync(k[m]));return h=e.utils.isArray(a)?h:h[0]}};e.extract=function(a,d){var b="",c=function(a,b){var d=~b.indexOf("#")?b.split("#")[1]:"",c=d?0:~b.indexOf("[")?parseInt(b.match(/\[(\d+)\]/)[1]):0,e=(d?b.split("#")[0]:c?b.split("[")[0]:b).toLowerCase();
    if(a==document&&"html"==e&&0==c)return document.getElementsByTagName("html")[0];if(~b.indexOf("#"))return document.getElementById(b.split("#")[1]);var g=a.firstChild;if(!g)return null;var f=0;for(c=0!=c?c-1:c;g;){if(1==g.nodeType){if(g.tagName.toLowerCase()==e&&""!=d&&g.id==d||g.tagName.toLowerCase()==e&&f==c&&""==d)return g;g.tagName.toLowerCase()==e&&f++}g=g.nextSibling}},e=function(a,b){a=a.split("/");for(var d=c(b||document,a[1]),e=2;e<a.length;e++){if(null==d)return null;d=c(d,a[e])}return d},
    h=function(){for(var a={},b=f.document.getElementsByTagName("META")||[],d=0,c=b.length;d<c;d++){var e=b[d].name||b[d].getAttribute("property")||"";0!==e.length&&(a[e]=b[d].content)}return a}(),g=function(a){var b=h[a];if(b)return b;b=f.document.getElementsByTagName("META")||[];for(var d=0,c=b.length;d<c;d++){var e=b[d].name||b[d].getAttribute("property")||"";if(a==e)return b[d].content}},q=function(a){return(val=(new RegExp("&"+a+"=([^&]*)")).exec(f.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:
    ""},r=function(a){return(val=(new RegExp("^"+a+"=.*|;\\s*"+a+"=.*")).exec(f.document.cookie))?val[0].split("=")[1].split(";")[0]:""},m=function(a){(a=l(a))&&a.nodeType&&1==a.nodeType&&(a=a.value||a.innerHTML||"");return a.toString().replace(/\n|\r|\s\s+/g,"")||""},l=function(a){var b="";if(0==a.indexOf("/HTML/BODY"))b=e(a);else try{b=eval(a)}catch(A){b=""}return b};try{return d?"meta"==d?b=g(a):"cookie"==d?b=r(a):"param"==d?b=q(a):"content"==d?b=m(a):"event"==d?b=l(a):"var"==d&&(b=f[a]):b=g(a)||r(a)||
    q(a)||m(a)||l(a)||f[a]||"",b||""}catch(x){return""}};if("undefined"==typeof h)var h={exports:{}};return e}(window),window[ensightenOptions.ns].data.defineEngine("store",function(){function f(a){return function(){var d=Array.prototype.slice.call(arguments,0);d.unshift(b);k.appendChild(b);b.addBehavior("#default#userData");b.load(h);d=a.apply(store,d);k.removeChild(b);return d}}function p(a){return a.replace(l,"___")}var l=RegExp("[!\"#$%&'()*+,/\\\\:;<=>?@[\\]^`{|}~]","g"),c={},e=window,m=e.document,
    h="localStorage",a,d=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};c.set=function(a,b){};c.get=function(a){};c.remove=function(a){};c.clear=function(){};try{if(h in e&&e[h]){var b=e[h];c.set=function(a,c){var e,g=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(d(a)){var f=0;for(e=a.length;f<e;f++)b.setItem(a[f],"string"===typeof c[f]?c[f]:g.stringify(c[f]))}else b.setItem(a,"string"===typeof c?c:g.stringify(c))};c.get=function(a){if(d(a)){var c=
    {},e;var f=0;for(e=a.length;f<e;f++)c[a[f]]=b.getItem(a[f]);return c}return b.getItem(a)};c.remove=function(a){if(d(a)){var c;var e=0;for(c=a.length;e<c;e++)b.removeItem(a[e])}else b.removeItem(a)};c.clear=function(){b.clear()};c.all=function(){return b}}else if("globalStorage"in e&&e.globalStorage)b=e.globalStorage[e.location.hostname],c.set=function(a,c){if(d(a)){var e;var f=0;for(e=a.length;f<e;f++)b[a[f]]=c[f]}else b[a]=c},c.get=function(a){if(d(a)){var c={},e;var f=0;for(e=a.length;f<e;f++)c[a[f]]=
    b[a[f]]&&b[a[f]].value;return c}return b[a]&&b[a].value},c.remove=function(a){if(d(a)){var c;var e=0;for(c=a.length;e<c;e++)delete b[a[e]]}else delete b[a]},c.clear=function(){for(var a in b)delete b[a]},c.all=function(){return b};else if(m.documentElement.addBehavior){try{var t=new ActiveXObject("htmlfile");t.open();t.write('<script>document.w=window\x3c/script><iframe src="/favicon.ico"></frame>');t.close();var k=t.w.frames[0].document;b=k.createElement("div")}catch(g){b=m.createElement("div"),
    k=m.body}c.set=f(function(a,b,e){if(d(b)){var f;var g=0;for(f=b.length;g<f;g++){fixedKey=p(b[g]);if(void 0===e[g])return c.remove(fixedKey);a.setAttribute(fixedKey,e[g]);a.save(h)}}else{fixedKey=p(b);if(void 0===e)return c.remove(fixedKey);a.setAttribute(fixedKey,e);a.save(h)}});c.get=f(function(a,b){if(d(b)){var c={},e;var f=0;for(e=b.length;f<e;f++){var g=p(b[f]);c[b[f]]=a.getAttribute(g)}return c}b=p(b);return a.getAttribute(b)});c.remove=f(function(a,b){if(d(b)){var c;var e=0;for(c=b.length;e<
    c;e++)a.removeAttribute(p(b[e])),a.save(h)}else b=p(b),a.removeAttribute(b),a.save(h)});c.clear=f(function(a){var b=a.XMLDocument.documentElement.attributes;a.load(h);for(var d=0,c;c=b[d];d++)a.removeAttribute(c.name);a.save(h)});c.all=f(function(a){for(var b=a.XMLDocument.documentElement.attributes,d={},c=0,e;e=b[c];++c){var f=p(e.name);d[e.name]=a.getAttribute(f)}return d})}}catch(g){}var n={};for(a in c)n[a]=c[a];n.testStorage=function(){try{var a="tk_"+Math.ceil(5E7*Math.random());n.set(a,"test");
    if("test"===n.get(a))return n.remove(a),!0}catch(q){}return!1};c.utils=n;return window[ensightenOptions.ns].data.local=c}()),window[ensightenOptions.ns].data.defineEngine("cookie",function(f,p){var l=function(){return l.get.apply(l,arguments)},c=l.utils={isArray:Array.isArray||function(c){return"[object Array]"===Object.prototype.toString.call(c)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(c){return Array.prototype.slice.call(c)},getKeys:Object.keys||function(c){var e=
    [],f="";for(f in c)c.hasOwnProperty(f)&&e.push(f);return e},escape:function(c){return String(c).replace(/[,;"\\=\s%]/g,function(c){return encodeURIComponent(c)})},retrieve:function(c,f){return null==c?f:c},getAllCookies:function(){if(""===f.cookie)return{};for(var c=f.cookie.split("; "),m={},h=0,a=c.length;h<a;h++){var d=c[h].split("=");m[decodeURIComponent(d[0])]=decodeURIComponent(d[1])}return m},set:function(e,m,h){h=h||-1;if(c.isPlainObject(e))for(var a in e)e.hasOwnProperty(a)&&l.set(a,e[a],
    m);else if(c.isArray(e)){var d;a=0;for(d=e.length;a<d;a++)l.set(e[a],m[a],h)}else{a=h.expires!==p?h.expires:l.defaults.expires||"";"number"===typeof a&&(a=new Date(a));a=c.isPlainObject(a)&&"toGMTString"in a?";expires="+a.toGMTString():c.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;d=(d=h.path||l.defaults.path)?";path="+d:"";var b=h.domain||l.defaults.domain;b=b?";domain="+b:"";h=h.secure||l.defaults.secure?";secure":"";f.cookie=c.escape(e)+"="+c.escape(m)+a+d+b+h}},
    get:function(e,f){f=f||p;var h=c.getAllCookies();if(c.isArray(e)){for(var a={},d=0,b=e.length;d<b;d++)a[e[d]]=c.retrieve(h[e[d]],f),a[e[d]]===p&&(a[e[d]]=null);return a}a=c.retrieve(h[e],f);return a===p?null:a},getGMTString:function(c){var e=new Date;e.setTime(e.getTime()+864E5*c);return e.toGMTString()}};l.defaults={path:"/",expires:c.getGMTString(90)};l.set=function(e,f){c.set(e,f)};l.remove=function(e){e=c.isArray(e)?e:c.toArray(arguments);for(var f=0,h=e.length;f<h;f++)c.set(e[f],"",{expires:-1})};
    l.clear=function(){return l.remove(c.getKeys(c.getAllCookies()))};l.get=function(e,f){return c.get(e,f)};l.all=function(){return c.getAllCookies()};l.utils=c;return window[ensightenOptions.ns].data.cookie=l}(document)));
		
window[ensightenOptions.ns].ensEvent||(window[ensightenOptions.ns].ensEvent=function(p,u){var k={queue:{},pollQueue:{},pushTrigger:function(b,c){if("[object Array]"===Object.prototype.toString.call(b)){for(var g=0;g<b.length;g++)k.pushTrigger(b[g],c);return!0}if("string"!=typeof b)return!1;this.queue[b]=this.queue[b]||{fn:[]};"function"==typeof c&&this.queue[b].fn.push(c);return!0},callTrigger:function(b,c,g){if("string"!=typeof b)return!1;b=k.queue[b];if("object"==typeof b&&b.fn&&b.fn.length&&(0!=
b.fireOnFirstSet&&c==u||c!=u&&0!=b.fireOnUpdate))for(c=0;c<b.fn.length;c++)try{b.fn[c].call(this)}catch(n){p[ensightenOptions.ns].reportException(n)}},setPollOptions:function(b,c,g){this.queue[b]=this.queue[b]||{fn:[]};this.queue[b].fireOnFirstSet=c;this.queue[b].fireOnUpdate=g},callPoll:function(b,c,g,p,r){if("string"==typeof b&&c&&c.length&&!(1>c.length)){for(var n=0;n<c.length;n++)k.setPollOptions(c[n],p,r);k.pushWatch(b,c,g)}},pushWatch:function(b,c,g){this.pollQueue[b]||(this.pollQueue[b]={previousVal:u,
eventArr:[],valueFn:g});this.pollQueue[b].eventArr=this.pollQueue[b].eventArr.concat(c);this.pollQueue[b].valueFn=g},globalWatch:function(){setInterval(function(){for(var b in k.pollQueue){var c=k.pollQueue[b],g=c.valueFn(b);if(c.previousVal!==g&&null!==g&&""!==g){for(var n=0;n<c.eventArr.length;n++)k.callTrigger.call(p,c.eventArr[n],c.previousVal,g);k.pollQueue[b].previousVal=g}}},500)}};k.globalWatch();return{add:function(b,c){return k.pushTrigger(b,c)},get:function(b){return k.queue[b]},trigger:function(b,
c){return k.callTrigger.call(c||p,b)},poll:function(b,c,g,n,r){r=r||p[ensightenOptions.ns].data.resolve;return k.callPoll(b,c,r,g,n)}}}(window),function(p,u,k){u[p]=k()}("qwery",window[ensightenOptions.ns],function(){function p(){this.c={}}function u(a){return H.g(a)||H.s(a,"(^|\\s+)"+a+"(\\s+|$)",1)}function k(a,d){for(var e=0,f=a.length;e<f;e++)d(a[e])}function b(a){for(var d=[],e=0,f=a.length;e<f;++e)l(a[e])?d=d.concat(a[e]):d[d.length]=a[e];return d}function c(a){for(var d=0,e=a.length,f=[];d<
e;d++)f[d]=a[d];return f}function g(a){for(;(a=a.previousSibling)&&1!=a.nodeType;);return a}function n(a,d,e,f,b,h,l,c,g,k,y){var I,B,m;if(1!==this.nodeType||d&&"*"!==d&&this.tagName&&this.tagName.toLowerCase()!==d||e&&(I=e.match(Q))&&I[1]!==this.id)return!1;if(e&&(m=e.match(R)))for(a=m.length;a--;)if(!u(m[a].slice(1)).test(this.className))return!1;if(g&&v.pseudos[g]&&!v.pseudos[g](this,y))return!1;if(f&&!l)for(B in g=this.attributes,g)if(Object.prototype.hasOwnProperty.call(g,B)&&(g[B].name||B)==
b)return this;return f&&!x(h,S(this,b)||"",l)?!1:this}function r(a){return J.g(a)||J.s(a,a.replace(T,"\\$1"))}function x(a,d,e){switch(a){case "=":return d==e;case "^=":return d.match(w.g("^="+e)||w.s("^="+e,"^"+r(e),1));case "$=":return d.match(w.g("$="+e)||w.s("$="+e,r(e)+"$",1));case "*=":return d.match(w.g(e)||w.s(e,r(e),1));case "~=":return d.match(w.g("~="+e)||w.s("~="+e,"(?:^|\\s+)"+r(e)+"(?:\\s+|$)",1));case "|=":return d.match(w.g("|="+e)||w.s("|="+e,"^"+r(e)+"(-|$)",1))}return 0}function q(a,
d){var e=[],f=[],b,h,l=d,c=C.g(a)||C.s(a,a.split(K)),g=a.match(L);if(!c.length)return e;var m=(c=c.slice(0)).pop();c.length&&(b=c[c.length-1].match(M))&&(l=N(d,b[1]));if(!l)return e;var y=m.match(E);var v=l!==d&&9!==l.nodeType&&g&&/^[+~]$/.test(g[g.length-1])?function(a){for(;l=l.nextSibling;)1==l.nodeType&&(y[1]?y[1]==l.tagName.toLowerCase():1)&&(a[a.length]=l);return a}([]):l.getElementsByTagName(y[1]||"*");b=0;for(m=v.length;b<m;b++)if(h=n.apply(v[b],y))e[e.length]=h;if(!c.length)return e;k(e,
function(a){t(a,c,g)&&(f[f.length]=a)});return f}function t(a,d,e,b){function l(a,b,c){for(;c=U[e[b]](c,a);)if(f(c)&&n.apply(c,d[b].match(E)))if(b){if(h=l(c,b-1,c))return h}else return c}var h;return(h=l(a,d.length-1,a))&&(!b||z(h,b))}function f(a,d){return a&&"object"===typeof a&&(d=a.nodeType)&&(1==d||9==d)}function h(a){var d=[],e;var f=0;a:for(;f<a.length;++f){for(e=0;e<d.length;++e)if(d[e]==a[f])continue a;d[d.length]=a[f]}return d}function l(a){return"object"===typeof a&&isFinite(a.length)}
function N(a,d,e){return 9===a.nodeType?a.getElementById(d):a.ownerDocument&&((e=a.ownerDocument.getElementById(d))&&z(e,a)&&e||!z(a,a.ownerDocument)&&F('[id="'+d+'"]',a)[0])}function v(a,d){var e,h;var g=d?"string"==typeof d?v(d)[0]:!d.nodeType&&l(d)?d[0]:d:m;if(!g||!a)return[];if(a===window||f(a))return!d||a!==window&&f(g)&&z(a,g)?[a]:[];if(a&&l(a))return b(a);if(e=a.match(V)){if(e[1])return(h=N(g,e[1]))?[h]:[];if(e[2])return c(g.getElementsByTagName(e[2]));if(W&&e[3])return c(g.getElementsByClassName(e[3]))}return F(a,
g)}function y(a,d){return function(e){var f,b;O.test(e)?9!==a.nodeType&&((b=f=a.getAttribute("id"))||a.setAttribute("id",b="__qwerymeupscotty"),d(a.parentNode||a,'[id="'+b+'"]'+e,!0),f||a.removeAttribute("id")):e.length&&d(a,e,!1)}}var m=document,D=m.documentElement,F,Q=/#([\w\-]+)/,R=/\.[\w\-]+/g,M=/^#([\w\-]+)$/,X=/^([\w]+)?\.([\w\-]+)$/,O=/(^|,)\s*[>~+]/,Y=/^\s+|\s*([,\s\+~>]|$)\s*/g,A=/[\s>\+~]/,P=/(?![\s\w\-\/\?&=:\.\(\)!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,T=/([.*+?\^=!:${}()|\[\]\/\\])/g,
V=new RegExp(M.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),L=new RegExp("("+A.source+")"+P.source,"g"),K=new RegExp(A.source+P.source),E=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*~]?=)['"]?([ \w\-\/\?&=:\.\(\)!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),U={" ":function(a){return a&&a!==D&&a.parentNode},">":function(a,d){return a&&a.parentNode==d.parentNode&&a.parentNode},"~":function(a){return a&&
a.previousSibling},"+":function(a,d,e,f){return a?(e=g(a))&&(f=g(d))&&e==f&&e:!1}};p.prototype={g:function(a){return this.c[a]||void 0},s:function(a,d,e){d=e?new RegExp(d):d;return this.c[a]=d}};var H=new p,J=new p,w=new p,C=new p,z="compareDocumentPosition"in D?function(a,d){return 16==(d.compareDocumentPosition(a)&16)}:"contains"in D?function(a,d){d=9===d.nodeType||d==window?D:d;return d!==a&&d.contains(a)}:function(a,d){for(;a=a.parentNode;)if(a===d)return 1;return 0},S=function(){var a=m.createElement("p");
return(a.innerHTML='<a href="#x">x</a>',"#x"!=a.firstChild.getAttribute("href"))?function(a,e){return"class"===e?a.className:"href"===e||"src"===e?a.getAttribute(e,2):a.getAttribute(e)}:function(a,e){return a.getAttribute(e)}}(),W=!!m.getElementsByClassName,Z=m.querySelector&&m.querySelectorAll,aa=function(a,d){var e=[],f,b;try{if(9===d.nodeType||!O.test(a))return c(d.querySelectorAll(a));k(f=a.split(","),y(d,function(a,d){b=a.querySelectorAll(d);1==b.length?e[e.length]=b.item(0):b.length&&(e=e.concat(c(b)))}));
return 1<f.length&&1<e.length?h(e):e}catch(ba){}return G(a,d)},G=function(a,d){var e=[],f,b;a=a.replace(Y,"$1");if(f=a.match(X)){var l=u(f[2]);f=d.getElementsByTagName(f[1]||"*");var c=0;for(b=f.length;c<b;c++)l.test(f[c].className)&&(e[e.length]=f[c]);return e}k(f=a.split(","),y(d,function(a,f,h){l=q(f,a);c=0;for(b=l.length;c<b;c++)if(9===a.nodeType||h||z(l[c],d))e[e.length]=l[c]}));return 1<f.length&&1<e.length?h(e):e};A=function(a){"undefined"!==typeof a.useNativeQSA&&(F=a.useNativeQSA?Z?aa:G:
G)};A({useNativeQSA:!0});v.configure=A;v.uniq=h;v.is=function(a,d,e){if(f(d))return a==d;if(l(d))return!!~b(d).indexOf(a);for(var c=d.split(","),h;d=c.pop();)if(h=C.g(d)||C.s(d,d.split(K)),d=d.match(L),h=h.slice(0),n.apply(a,h.pop().match(E))&&(!h.length||t(a,h,d,e)))return!0;return!1};v.pseudos={};return v}),function(){function p(f,b,c){n||(n=window[ensightenOptions.ns].qwery);var h=n;if((h=h.call(c,b,c))&&0<h.length){if("_root"==b)f=c;else if(f===c)f=void 0;else{b:{for(var l=h.length,g=0;g<l;g++)if(f===
h[g]){h=!0;break b}h=!1}h||(f.parentNode?(r++,f=p(f.parentNode,b,c)):f=void 0)}return f}return!1}function u(f,b,c,g){q[f.id]||(q[f.id]={});q[f.id][b]||(q[f.id][b]={});q[f.id][b][c]||(q[f.id][b][c]=[]);q[f.id][b][c].push(g)}function k(f,b,c,g){if(g||c)if(g)for(var h=0;h<q[f.id][b][c].length;h++){if(q[f.id][b][c][h]===g){q[f.id][b][c].pop(h,1);break}}else delete q[f.id][b][c];else q[f.id][b]={}}function b(b,c,l){if(q[b][l]){var f=c.target||c.srcElement,h,k,m={},n=k=0;r=0;for(h in q[b][l])q[b][l].hasOwnProperty(h)&&
(k=p(f,h,t[b].element))&&g.matchesEvent(l,t[b].element,k,"_root"==h,c)&&(r++,q[b][l][h].match=k,m[r]=q[b][l][h]);c.stopPropagation=function(){c.cancelBubble=!0};for(k=0;k<=r;k++)if(m[k])for(n=0;n<m[k].length;n++){if(!1===m[k][n].call(m[k].match,c)){g.cancel(c);return}if(c.cancelBubble)return}}}function c(c,h,l,n){function f(c){return function(f){b(p,f,c)}}c instanceof Array||(c=[c]);l||"function"!=typeof h||(l=h,h="_root");var p=this.id,m;for(m=0;m<c.length;m++)q[p]&&q[p][c[m]]||g.addEvent(this,c[m],
f(c[m])),n?k(this,c[m],h,l):u(this,c[m],h,l);return this}function g(b,c,l,k){if("string"==typeof b&&"function"==typeof c||"string"==typeof c)g(document).on(b,c,l,k||!1);if(!(this instanceof g)){for(var f in t)if(t[f].element===b)return t[f];x++;t[x]=new g(b,x);t[x]._on=t[x].on;t[x].on=function(b,c,f,g){var h="function"==typeof c?c:f;if("function"==typeof c?f:g)b=[b],"string"==typeof c&&b.push(c),b.push(function(b){return function(c){c.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);
if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return b.call(this);"undefined"!=typeof c.preventDefault?c.preventDefault():c.returnValue=!1;b.call(this)}}(h)),this._on.apply(this,b);else return this._on.call(this,b,c,f)};return t[x]}this.element=b;this.id=c}var n,r=0,x=0,q={},t={};g.prototype.on=function(b,g,l){return c.call(this,b,g,l)};g.prototype.off=function(b,g,l){return c.call(this,b,g,l,!0)};g.cancel=function(b){b.preventDefault();b.stopPropagation()};g.addEvent=function(b,c,g){b.element.addEventListener(c,
g,"blur"==c||"focus"==c)};g.matchesEvent=function(){return!0};g.load=function(b){setTimeout(function(b,c){return function(){if(b.nodeName&&"a"==b.nodeName.toLowerCase()){if(c&&/^javascript\s*:/.test(c))return(new Function(unescape(c))).call(window);c&&(window.location.href=c)}}}(b,b.href||""),750)};window[ensightenOptions.ns].Delegate=g}(),function(p){var u=p.addEvent;p.addEvent=function(k,b,c){if(k.element.addEventListener)return u(k,b,c);"focus"==b&&(b="focusin");"blur"==b&&(b="focusout");k.element.attachEvent("on"+
b,c)};p.cancel=function(k){k.preventDefault&&k.preventDefault();k.stopPropagation&&k.stopPropagation();k.returnValue=!1;k.cancelBubble=!0}}(window[ensightenOptions.ns].Delegate),window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate);
Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)};p[i].q=p[i].q||[]}})(window,document,null,null,"sp")},2234110,498763);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;!function(a,b){var c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C;c=function(a,b){return Array.prototype.indexOf.call(b,a)>-1},d=function(a){function b(){var a=[];return d.forEach(function(b){a.push(b.toString())}),a}var c={},d=[];return c.add=function(a){d.push(a)},c.process=function(a,b){var c=[];d.forEach(function(b){a.call(null,b)||c.push(b)}),b&&(d=
c)},c.contains=function(c){return a(b(),c)},c.size=function(){return d.length},c.toString=function(){return b().join()},c.clear=function(){d=[]},c.get=function(){return b()},c}(c),e=function(){function a(a,b){this.eventId=a,this.data=b}return a.prototype.toString=function(){return this.eventId},a}(),f=function(){return function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}}(),g=function(){return function(a,b){var c=Object.prototype.toString.call(b).slice(8,-1);return void 0!==b&&null!==b&&
c===a}}(),h=function(a){return a.bind(null,"String")}(g),i=function(){function a(a){return JSON.parse(JSON.stringify(a))}return a}(),j={enable:!1,out:function(a){this.enable&&console.log(a)}},k=function(a){function b(b){this.name="InvalidArgumentError",this.message=b||"",a.out(this.name+": "+this.message)}return b.prototype=new Error,b}(j),l=function(a){function b(b,c){this.name="ValidationError",this.errorType=c||"",this.message=b||"",a.out(this.name+" ("+this.errorType+"): "+this.message)}return b.prototype=
new Error,b}(j),m=function(a){return a.bind(null,"Object")}(g),n=function(a){return a.bind(null,"Array")}(g),o=function(a){return a.bind(null,"Number")}(g),p=function(a,b,c,d,e,f){var g={PIINPI:{PhoneNumber:/^(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?$/,Email:/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}/,
SSN:/\d{3}\-\d{2}\-\d{4}/,CCN:/\d{4}\-\d{4}\-\d{4}\-\d{4}/}},h={"PII-NPI":function(d){var e=g.PIINPI;if(!c(d))throw new a("datum must be a string.");for(var f in e)if(e[f].test(d))throw new b("Data object compromises PII-NPI information",f);return d}},i=function(a){return void 0===a?a:(d(a)?Object.keys(a).forEach(function(b){a[b]=i(a[b])}):e(a)?a.forEach(function(b,c){a[c]=i(b)}):(a=f(a)?a.toString():a,Object.keys(h).forEach(function(b){a=h[b].call(this,a)})),a)};return{execute:i}}(k,l,h,m,n,o),q=
function(a,b,c,d,e){var f={};return{has:function(b){return a(f,b)},execute:function(a,b){var g={};return d.out("Executing subscriber(s) for "+a),f[a].forEach(function(f){var h=f.auxData;if(f.isEnabled){if(!f.skipValidation)try{b=e.execute(b),h&&h.data&&h.data.forEach(function(a,b,c){c[b]=e.execute(a)})}catch(i){return d.out("Validation Error - Aborting track execution for "+a),void(g[f.title]=!1)}f.track(c(b),h),g[f.title]=!0}else g[f.title]=!1}),g},add:function(a,b){this.has(a)||(f[a]=[]);var c=
f[a].findIndex(function(a){return a.title===b.title});c>-1?f[a][c]=b:f[a].push(b)},clear:function(a){if(a&&b(a))return void Object.keys(f).forEach(function(b){var c=[];f[b].forEach(function(b){b.title!==a&&c.push(b)}),f[b]=c});void 0!==a&&null!==a||(f={})},get:function(a,b){return 0===arguments.length?f:1===arguments.length?f[a]:f[a].find(function(a){return a.title===b})}}}(f,h,i,j,p),r=function(a){function b(c,d){var e=function(a){return Object.keys(a)},f=function(a){return Object.keys(a).length},
g=e(c),h=e(d);if(f(c)!==f(d))return!1;for(var i=0;i<g.length;i++){if(void 0===d[g[i]]||void 0===c[h[i]]||typeof c[h[i]]!=typeof d[g[i]])return!1;if(!a(c[g[i]])&&c[g[i]].toString()!=d[g[i]].toString())return!1;if(a(c[g[i]]))if(!b(c[g[i]],d[g[i]]))return!1}return!0}return b}(m),s=function(a){var b={threshold:300,lastEvent:{}};return{getThreshold:function(){return b.threshold},getLastEvent:function(){return b.lastEvent},clear:function(){b.lastEvent={}},execute:function(c,d){return b.lastEvent.id!=c?
(b.lastEvent={id:c,data:d,executionTime:new Date},!1):new Date-b.lastEvent.executionTime<b.threshold&&a(b.lastEvent.data,d)?(b.lastEvent.executionTime=new Date,!0):(b.lastEvent.data=d,b.lastEvent.executionTime=new Date,!1)}}}(r),t=function(a){return a.bind(null,"Function")}(g),u=function(a,b,c,d,e,f,g,h,i,j){var k,l=function(d,h){if(!f(d))throw new i("eventId must be a string.");if(!g(h))throw new i("Data must be an object.");if(e.execute(d,h))return!1;j.out(d+" published with data:\n"+JSON.stringify(h,
null,4));var k=new b(d,h);return a.add(k),!!c.has(d)&&(c.execute(d,h),!0)},m=function(a,b){if(!f(a))throw new i("eventId must be a string");if(!g(b))throw new i("subscriber must be an object");c.add(a,b)},n=function(b,c){function e(a){Object.keys(c).forEach(function(b){if(a.eventId===b){j.out("Processing: "+a.eventId);var e=c[b],f=a.data;if(!e.skipValidation)try{f=d.execute(f)}catch(g){return void j.out("Validation Error - Aborting track execution for "+b)}e.track(f)}})}if(!f(b))throw new i("utilityName must be a string");
if(!g(c))throw new i("subscriberMap must be an object");Object.keys(c).forEach(function(a){var d=c[a];if(j.out("Adding subscriber for "+a),!h(d.track))return void console.warn("Invalid Subscriber: Subscriber for "+a+" in "+b+" map does not have track function.");d.title=b,m(a,d)}),j.out("Subscriber map for "+b+" successfully added!!!"),a.size()&&(j.out("Processing "+a.size()+" eventIds in history"),a.process(e,!1))},o=function(a,b,d){var e=c.get(a,b);e.auxData=e.auxData||[],e.auxData.push(d),c.add(a,
e)};return function(b){return j.enable=b,b&&j.out("Debug cookie is present and active"),k={publishEvent:l,addListenerMap:n,addAuxData:o},j.enable&&(k.getEventIds=c.get,k.clearHistory=a.clear,k.clearEventIds=c.clear,k.getEventIdsInHistory=a.get,k.clearThrottler=e.clear),k}}(d,e,q,p,s,h,m,t,k,j),v=function(){function a(a,b,c){c[b]=a&&a.trim()}function b(a){return!!a}var c=arguments;if(c.length){var d,e=new RegExp("^[:|,-]"),f=c[0].match(e),g=f?[].shift.call(c):":";return[].forEach.call(c,a),d=[].filter.call(c,
b),[].join.call(d,g)}},w={pageName:"pageName",channel:"channel",section:"prop1",subSection:"prop2",pageType:"prop8",country:"eVar10",language:"eVar11",framework:"prop50",features:"prop14",system:"eVar24",nonpageviewpath:"prop9"},x=function(a,b,c){var d,e,f=function(a){return"lob"===a?"channel":a},g=function(a){var c="";return b(a)?a.forEach(function(a){a.prop&&(c+=e(f(a.prop))),a.value&&(c+=a.value)}):c=e(f(a)),c},h=function(a){var b="";return a.value&&(b=a.value),b},i=function(b,e){var f,i,j,k;c(e)?
(f=e.pre,i=e.suffix,k=e.value||b,j=e.scVar):(j=e,k=b),f&&(k=a(g(f),k)),i&&(k=a(k,h(i))),d[j]=k};return function(a,c,f){return d={},e=f,b(a)?a.forEach(i.bind(null,c)):i(c,a),d}}(v,n,m),y=function(a,b){var c,d={},e=[];return[a,b].forEach(function(a){for(c in a)"events"===c?e.push(a[c]):d[c]=a[c]}),e.length&&(d.events=e.sort().join()),d},z=function(a,c,d,e,f,g,h){var i,j,k,l,m,n,o,p,q,r=["channel","prop4","eVar10","eVar11","prop11","eVar24"],s="tlDataPrevPage",t="pvDataPrevPage",u=function(a){var b=
{};return a?(Object.keys(a).forEach(function(c){var g=e(d[c],a[c],p);b=f(b,g)}),Object.keys(b).forEach(function(a){b[a]=b[a].toLowerCase()}),b):b},v=function(b){a.out(b.type+": "+performance.now());var c=new Date((new Date).getTime()+12E4);m&&(a.out("Abort track call and save data"),clearTimeout(m),n.Cookies.set(s,JSON.stringify(k),c.toGMTString()))},w=function(b){a.out(b.type+": "+performance.now())};return i={trackCall:function(b,c){var d,e=o.target;if(Object.keys(b).forEach(function(a){b[a]=b[a].toLowerCase(),
h(a,r)||r.push(a)}),b.linkTrackEvents=b.events||"None",b.linkTrackVars=r.join(),k=f(u(o.dataLayer),b),k.linkName||(k.linkName="On click of "+c),d=[!0,"o","",k],e&&(e.account||e.un)){k.account=e.account,d[3]=k;var g=function(){a.out("Track link call with data: "+JSON.stringify(k,null,4)),e.tl.apply(e,d),m=0};return n.executeTlImmediate?g():(a.out("Delaying tl call by 20 ms"),m=q(g,20)),!0}a.out("s not yet available. Track link call will be processed after pageView"),l=l||[],l.push(d)},pageViewCall:function(c){if(n.nopageviewfire)return!1;
Object.keys(c).forEach(function(a){c[a]=c[a].toLowerCase()});var d=f(j,c);d.pageURL=b.location.href,d.referrer=document.referrer;var e=n.Cookies.get(t),g=e?JSON.parse(e):[];g.push(d);var h=new Date((new Date).getTime()+12E4);return n.Cookies.set(t,JSON.stringify(g),h.toGMTString(),!0),a.out("Executing trackerFramework executeAutoLaunch with data: "+JSON.stringify(d,null,4)),o.executeAutoLaunch(null,d),!0},setTaxonomy:function(a){if(a&&g(a)){var d,e=a.level1||"",f=a.level2||"",h=a.level3||"",i=a.level4||
"",k=a.level5||"",l=c(e,f),m=h?c(l,h):"",n=i?c(m,i):"",p=c(l,h,i,k);d={channel:e,section:l,subSection:m,features:n,pageName:p,country:a.country||"",language:a.language||"",system:a.system||"",nonpageviewpath:p||"",framework:"master-subscriber"},b.sc_level1=a.level1||"",b.sc_level2=a.level2||"",b.sc_level3=a.level3||"",b.sc_level4=a.level4||"",b.sc_level5=a.level5||"",b.sc_country=a.country||"",b.sc_language=a.language||"",b.sc_system=a.system||"",o.dataLayer=d,j=u(d)}}},function(a,b,c){var d,e,f=
"beforeunload",g="unload",h="on";return n=a,n.tlDataKey=s,n.pvDataKey=t,n.getTlArgsQueue=function(){return l},n.resetTlArgsQueue=function(){l=null},o=a.trackerFramework,p=o.getDataLayerProperty.bind(o),d=b.addEventListener,e=b.attachEvent,q=b.setTimeout,d?(d(f,v,!1),d(g,w,!1)):e&&(e(h+f,v),e(h+g,w)),c&&(i.baseAnalyticsData=function(){return j}),i}}(j,v,w,x,y,m,c),A=function(a,b,c,d,e){return{selfService:{oneTimePayment:{start:"event72",complete:"event73"},autoPay:{start:"event74",complete:"event75"},
start:"event6",complete:"event7",vars:{scVar:"eVar19",pre:"lob"}},application:{start:"event19",complete:"event5",decision:{approved:"event23",pending:"event24",decline:"event25",softDecline:"event26"},vars:{scVar:"eVar33",pre:"lob"}},enrollment:{start:"event13",complete:"event14",vars:{scVar:"eVar23",pre:"lob"}},intercept:{banner:"event15",click:"event10",accept:"event18",vars:["eVar18","list1"]},banner:{display:"event16",click:"event17",vars:"list1"},interactionMessage:{display:{events:"event16",
vars:"list1"},click:{events:"event17",vars:"eVar18"}},login:{events:"event22",vars:{scVar:"eVar48",pre:"section"}},chat:{events:function(a){return d(a,["proactive","reactive","reject"])?"event3":null},vars:[{scVar:"eVar5",pre:"lob",value:"chat"},{scVar:"prop9",pre:[{prop:"system"},{value:" chat"}]},{scVar:"linkName",value:"on chat interaction"}]},process:function(d,f,g){var h=[],i={},j=this[d];if(b(f))Object.keys(f).forEach(function(c){var d,k;"type"!==c&&(d=f.type?this[f.type][c]:this[c],k=f[c],
b(d)?e(d,k)?d=d[k]:(i=a(d.vars,k,g),d=d.events):i=a(j.vars,k,g),h.push(d))},j);else{if(c(j.events)){var k=j.events.call(null,f);k&&h.push(k)}else h.push(j.events);i=a(j.vars,f,g)}return h.length&&(i.events=h.join()),i}}}(x,m,t,c,f),B={name:{scVar:"prop9",pre:"pageName"},nav:{scVar:"prop9",pre:"lob"},selection:{scVar:"prop17",pre:"lob"},filter:{scVar:"prop30",pre:"lob"},error:{scVar:"prop26",pre:"lob"},outageMessage:{scVar:"prop26",pre:"lob"},searchResults:"prop12",searchTerm:"prop13",promotionId:"prop34",
deviceType:"prop40",accountType:"prop49",suggestedTerm:{scVar:"prop51",pre:"lob"},suggestedLink:{scVar:"prop52",pre:"lob"},clientCorrelationId:"prop54",apiErrorCode:"prop59",lob:"prop64",iphoneRes:"prop27",mobileTrafficType:"prop28",dealerId:"prop37",altCustId:"prop38",linkedAppsTile:"prop41",kmInfo:{scVar:"prop42",pre:"lob"},altCif:"prop20",externalId:"campaign",accountAction:{scVar:"eVar20",pre:"lob"},solicitationId:"eVar35",testCell:"eVar36",applicationId:"eVar37",userType:{scVar:"eVar52",pre:"lob"},
clientId:{scVar:"eVar38",pre:"lob"},pffSrcId:"eVar46",brand:"eVar58",portalTestGroup:"eVar9",offerType:"eVar29",audienceType:"eVar57",passTrack:"eVar34",vin:"eVar49",geoLocation:"eVar54",customerType:"eVar12",google_click_identifier:"eVar19",keywords:"eVar43",entTestGroup:["prop7","eVar60"],akamaiTest:"eVar26",testGroup:"eVar59",campaignID:"eVar71",productName:{scVar:"eVar16",pre:"lob"},stepsImpression:"eVar16",neustarSegment:"eVar5",challengeApp:"eVar70"},C=function(a,b,c,d,e,f){return function(g,
h,i,j){var k=j.trackerFramework.getDataLayerProperty.bind(j.trackerFramework);return function(l){if(null===l)return!1;var m={},n=!1;if(b(l,"taxonomy")&&(n=!0,g(l.taxonomy),delete l.taxonomy),b(l,"applicationId")&&(j.trackerFramework.dataLayer.applicationId=l.applicationId),b(l,"name")){var o=j.trackerFramework.getWhiteList(),p=l.name.toLowerCase();if(o&&!c(p,o))return j.reportException(new Error("name "+l.name+" is not in whitelist")),!1}return Object.keys(l).forEach(function(c){var g;if(l[c]){if(b(d,
c))return g=d.process(c,l[c],k),void(m=a(m,g));b(e,c)&&(g=f(e[c],l[c],k),m=a(m,g))}}),(n?h:i).call(null,m,l.name||l.nav)}}}(y,f,c,A,B,x);var D=a.Cookies.test("enableDebug"),E=u(D),F=z(a,b),G=C(F.setTaxonomy,F.pageViewCall,F.trackCall,a);E.addListenerMap("SiteCatalyst",{trackAnalytics:{isEnabled:!0,track:G}}),b.publisherFW=E}(Bootstrapper,window)},2886621,[2333784,2881592],498463,[498462,498464]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Array.prototype.filter||(Array.prototype.filter=function(a){if(void 0===this||null===this)throw new TypeError;var b=Object(this),c=b.length>>>0;if("function"!=typeof a)throw new TypeError;for(var d=[],e=arguments.length>=2?arguments[1]:void 0,f=0;f<c;f++)if(f in b){var g=b[f];a.call(e,g,f,b)&&d.push(g)}return d}),Array.prototype.findIndex||Object.defineProperty(Array.prototype,
"findIndex",{value:function(a){if(null==this)throw new TypeError('"this" is null or not defined');var b=Object(this),c=b.length>>>0;if("function"!=typeof a)throw new TypeError("predicate must be a function");for(var d=arguments[1],e=0;e<c;){var f=b[e];if(a.call(d,f,e,b))return e;e++}return-1},configurable:!0,writable:!0}),Array.prototype.forEach||(Array.prototype.forEach=function(a,b){var c,d;if(null===this)throw new TypeError(" this is null or not defined");var e=Object(this),f=e.length>>>0;if("function"!=
typeof a)throw new TypeError(a+" is not a function");for(arguments.length>1&&(c=b),d=0;d<f;){var g;d in e&&(g=e[d],a.call(c,g,d,e)),d++}}),Function.prototype.bind||(Function.prototype.bind=function(a){if("function"!=typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice.call(arguments,1),c=this,d=function(){},e=function(){return c.apply(this instanceof d?this:a,b.concat(Array.prototype.slice.call(arguments)))};return this.prototype&&
(d.prototype=this.prototype),e.prototype=new d,e}),"function"!=typeof Object.assign&&Object.defineProperty(Object,"assign",{value:function(a,b){if(null==a)throw new TypeError("Cannot convert undefined or null to object");for(var c=Object(a),d=1;d<arguments.length;d++){var e=arguments[d];if(null!=e)for(var f in e)Object.prototype.hasOwnProperty.call(e,f)&&(c[f]=e[f])}return c},writable:!0,configurable:!0}),Object.keys||(Object.keys=function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),
c=["toString","toLocaleString","valueOf","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","constructor"],d=c.length;return function(e){if("object"!=typeof e&&("function"!=typeof e||null===e))throw new TypeError("Object.keys called on non-object");var f,g,h=[];for(f in e)a.call(e,f)&&h.push(f);if(b)for(g=0;g<d;g++)a.call(e,c[g])&&h.push(c[g]);return h}}()),String.prototype.includes||(String.prototype.includes=function(a,b){return"number"!=typeof b&&(b=0),!(b+a.length>this.length)&&-1!==this.indexOf(a,
b)}),String.prototype.trim||function(){var a=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;String.prototype.trim=function(){return this.replace(a,"")}}(),document.getElementsByClassName||(document.getElementsByClassName=function(a){var b,c,d,e=document,f=[];if(e.querySelectorAll)return e.querySelectorAll("."+a);if(e.evaluate)for(c=".//*[contains(concat(' ', @class, ' '), ' "+a+" ')]",b=e.evaluate(c,e,null,0,null);d=b.iterateNext();)f.push(d);else for(b=e.getElementsByTagName("*"),c=new RegExp("(^|\\s)"+a+
"(\\s|$)"),d=0;d<b.length;d++)c.test(b[d].className)&&f.push(b[d]);return f}),function(a,b){"object"==typeof exports&&"undefined"!=typeof module?b():"function"==typeof define&&define.amd?define(b):b()}(0,function(){function a(){}function b(a,b){return function(){a.apply(b,arguments)}}function c(a){if(!(this instanceof c))throw new TypeError("Promises must be constructed via new");if("function"!=typeof a)throw new TypeError("not a function");this._state=0,this._handled=!1,this._value=void 0,this._deferreds=
[],i(a,this)}function d(a,b){for(;3===a._state;)a=a._value;if(0===a._state)return void a._deferreds.push(b);a._handled=!0,c._immediateFn(function(){var c=1===a._state?b.onFulfilled:b.onRejected;if(null===c)return void(1===a._state?e:f)(b.promise,a._value);var d;try{d=c(a._value)}catch(g){return void f(b.promise,g)}e(b.promise,d)})}function e(a,d){try{if(d===a)throw new TypeError("A promise cannot be resolved with itself.");if(d&&("object"==typeof d||"function"==typeof d)){var e=d.then;if(d instanceof
c)return a._state=3,a._value=d,void g(a);if("function"==typeof e)return void i(b(e,d),a)}a._state=1,a._value=d,g(a)}catch(h){f(a,h)}}function f(a,b){a._state=2,a._value=b,g(a)}function g(a){2===a._state&&0===a._deferreds.length&&c._immediateFn(function(){a._handled||c._unhandledRejectionFn(a._value)});for(var b=0,e=a._deferreds.length;b<e;b++)d(a,a._deferreds[b]);a._deferreds=null}function h(a,b,c){this.onFulfilled="function"==typeof a?a:null,this.onRejected="function"==typeof b?b:null,this.promise=
c}function i(a,b){var c=!1;try{a(function(a){c||(c=!0,e(b,a))},function(a){c||(c=!0,f(b,a))})}catch(d){if(c)return;c=!0,f(b,d)}}var j=function(a){var b=this.constructor;return this.then(function(c){return b.resolve(a()).then(function(){return c})},function(c){return b.resolve(a()).then(function(){return b.reject(c)})})},k=setTimeout;c.prototype.catch=function(a){return this.then(null,a)},c.prototype.then=function(b,c){var e=new this.constructor(a);return d(this,new h(b,c,e)),e},c.prototype.finally=
j,c.all=function(a){return new c(function(b,c){function d(a,g){try{if(g&&("object"==typeof g||"function"==typeof g)){var h=g.then;if("function"==typeof h)return void h.call(g,function(b){d(a,b)},c)}e[a]=g,0==--f&&b(e)}catch(i){c(i)}}if(!a||void 0===a.length)throw new TypeError("Promise.all accepts an array");var e=Array.prototype.slice.call(a);if(0===e.length)return b([]);for(var f=e.length,g=0;g<e.length;g++)d(g,e[g])})},c.resolve=function(a){return a&&"object"==typeof a&&a.constructor===c?a:new c(function(b){b(a)})},
c.reject=function(a){return new c(function(b,c){c(a)})},c.race=function(a){return new c(function(b,c){for(var d=0,e=a.length;d<e;d++)a[d].then(b,c)})},c._immediateFn="function"==typeof setImmediate&&function(a){setImmediate(a)}||function(a){k(a,0)},c._unhandledRejectionFn=function(a){"undefined"!=typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a)};var l=function(){if("undefined"!=typeof self)return self;if("undefined"!=typeof window)return window;if("undefined"!=typeof global)return global;
throw new Error("unable to locate global object");}();l.Promise?l.Promise.prototype.finally||(l.Promise.prototype.finally=j):l.Promise=c}),function(a){a.console=a.console||{};for(var b,c,d=a.console,e={},f=function(){},g="memory".split(","),h="assert,clear,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profiles,profileEnd,show,table,time,timeEnd,timeline,timelineEnd,timeStamp,trace,warn".split(",");b=g.pop();)d[b]||(d[b]=e);for(;c=h.pop();)d[c]||
(d[c]=f)}("undefined"==typeof window?this:window),function(){if("performance"in window||(window.performance={}),Date.now=Date.now||function(){return(new Date).getTime()},!("now"in window.performance)){var a=Date.now();performance.timing&&performance.timing.navigationStart&&(a=performance.timing.navigationStart),window.performance.now=function(){return Date.now()-a}}}();!function(a,b){var c,d,e,f,g;c=function(){return function(a,b){for(var a,c=0,d=String.prototype.indexOf.bind(a,"."),e=d();-1!==e;)c++,
e=d(e+1);var f=function(b){var c=a.lastIndexOf(".");if(c>=0){for(;c>=0&&b>1;)c=a.lastIndexOf(".",c-1),b--;return c>0?a.substring(c):a}};return{get:function(a,c){for(var d=b.cookie.split(";"),e=0;e<d.length;e++){var f=d[e].replace(/^\s+/,"").split(/=(.+)/);if(f[0]==a)return c?f[1]:decodeURIComponent(f[1])}return null},set:function(a,d,e,g){for(var h=!1,i=2;!h&&i<=c&&(b.cookie=a+"\x3d"+encodeURIComponent(d)+(e?";expires\x3d"+e:"")+";path\x3d/;domain\x3d"+f(i++),h=this.get(a)===d,!g););return h},del:function(a){return this.set(a,
"",new Date)},test:function(a){return!!this.get(a)}}}}(),d=function(a){return function(b,c,d){var e=arguments.length>1?2==arguments.length?"object"==typeof arguments[1]&&null!==arguments[1]?c:a:c:a,f=arguments.length>1&&(2==arguments.length?"boolean"==typeof arguments[1]&&c:d),g=[];e="object"==typeof e?e:a;for(var h=e.getElementsByTagName("*"),i=0,j=h.length;i<j;i++)"string"==typeof h[i].className&&(!f&&h[i].className==b||f&&~h[i].className.indexOf(b))&&g.push(h[i]);return g}},e=function(){return function(a,
b){return function(a,c){if(!this.params||c){var d=c||b.location.search,e=d.replace(/^\?/,""),f={};e=e.split("\x26");for(var g=0;g<e.length;g++){var h=e[g].split("\x3d");f[h[0]]=decodeURIComponent(h[1])}if(c)return f[a]||"";this.params=f}return this.params[a]||""}.bind(a)}}(),f=function(){return function(a,b){var c={watchers:[]},d={};return c.options=b||{},c.options.interval=c.options.interval||50,c.Watcher=function(a,b){var c={};return c.propertyFn=a,c.lastValue=void 0,c.options=b,c.change=function(a,
b){},c},c.doChecks=function(){for(var a=0;a<c.watchers.length;a++){var b=c.watchers[a],d=b.propertyFn?b.propertyFn():null;b.lastValue!=d&&(b.change(b.lastValue,d),b.lastValue=d)}c.resetTimer()},c.resetTimer=function(){a.setTimeout(function(){c.doChecks()},c.options.interval)},c.addWatcher=function(a,b){var d=c.Watcher(a,b);return c.watchers.push(d),d},d={create:c.addWatcher},c.doChecks(),d}}(),g=function(){return function(a){return/^prod/.test(a.ensightenOptions.publishPath)}}(),a.Cookies=c(b.location.hostname,
b.document),a.getElementsByClassName=d(b.document),a.getQueryParam=e(a,b),a.propertyWatcher=f(b),a.isProd=g(a)}(Bootstrapper,window)},2881592,498464);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var undefinedPropPrefix="undef-",undefRegex=new RegExp(undefinedPropPrefix+"(\\w*)"),isArray=function(obj){var type=Object.prototype.toString.call(obj).slice(8,-1);return obj!==undefined&&obj!==null&&type==="Array"},processTlQueue=function(tlArgsQueue,fw){console.log("Triggering "+tlArgsQueue.length+" track calls in queue");var keys=Object.keys(fw.dataLayer);tlArgsQueue.forEach(function(tlArgsArray){var dataObj=
tlArgsArray[3];Object.keys(dataObj).forEach(function(key){var value=dataObj[key];if(value){value=value.replace(undefRegex,function(match,p1){if(!fw.dataLayer.hasOwnProperty(p1)){var filteredKeys=keys.filter(function(key,index,array){return key.toLowerCase()===p1.toLowerCase()?key:null});p1=filteredKeys.length?filteredKeys[0]:null}return fw.dataLayer[p1]});dataObj[key]=value}});tlArgsArray[3]=dataObj;fw.target.tl.apply(fw.target,tlArgsArray)})},getReportSuiteId=function(dataLayer){dataLayer=dataLayer||
{};var country=dataLayer.country||"",system=dataLayer.system||"",channel=dataLayer.channel||"";Bootstrapper.varLOB=Bootstrapper.getVarLOB(system,channel);return Bootstrapper.getSCAccount(system,channel,country)};Bootstrapper.trackerFramework=function(){var tries=0,maxTries=70,interval=100;var cArray=function(){var funcs=[],hasRun=false;return{add:function(f){if(hasRun){try{f()}catch(e){Bootstrapper.reportException(e)}return}if(typeof f!=="function")return;funcs[funcs.length]=f},clear:function(){funcs=
[]},exec:function(){var toRun=funcs,i,len;hasRun=true;for(i=0,len=toRun.length;i<len;i++)try{toRun[i].call(window)}catch(e){Bootstrapper.reportException(e)}},haveRun:function(){return hasRun},getFuncs:function(){return funcs}}};return{prePopulate:cArray(),postPopulate:cArray(),tempPopulate:cArray(),globalData:cArray(),localData:cArray(),globalEvents:cArray(),localEvents:cArray(),execute:function(data){this.prePopulate.exec();this.events=this.getEvents();this.postPopulate.exec();this.tempPopulate.exec();
this.target.t(data);var tlArgsQueue=Bootstrapper.getTlArgsQueue();if(isArray(tlArgsQueue)&&tlArgsQueue.length){processTlQueue(tlArgsQueue,this);Bootstrapper.resetTlArgsQueue()}},getData:function(){var key,retObj={},i,l,tempObj;var globalFuncs=this.globalData.getFuncs();for(i=0,l=globalFuncs.length;i<l;i++){tempObj=globalFuncs[i].call(window);for(key in tempObj)if(tempObj[key])retObj[key]=tempObj[key]}var localFuncs=this.localData.getFuncs();for(i=0,l=localFuncs.length;i<l;i++){tempObj=localFuncs[i].call(window);
for(key in tempObj)if(tempObj[key])retObj[key]=tempObj[key]}for(key in retObj)if(typeof retObj[key]=="string")retObj[key]=retObj[key].toLowerCase();return retObj},getEvents:function(){var retEvents="",i,l,temp;var globalFuncs=this.globalEvents.getFuncs();for(i=0,l=globalFuncs.length;i<l;i++){temp=globalFuncs[i].call(window);retEvents+=retEvents!=""?","+temp:temp}var localFuncs=this.localEvents.getFuncs();for(i=0,l=localFuncs.length;i<l;i++){temp=localFuncs[i].call(window);retEvents+=retEvents!=""?
","+temp:temp}return retEvents},autoLaunch:function(o,data){var dlTries=0,dlMaxTries=20,dlInterval=100;var waitForGlobalDataLayer=function(){if(Bootstrapper.trackerFramework.globalData.getFuncs().length){Bootstrapper.trackerFramework.executeAutoLaunch(o,data);return}if(++dlTries<dlMaxTries)setTimeout(waitForGlobalDataLayer,dlInterval);else{console.warn("Global Data layer deployment not available! Aborting autoLaunch call after "+dlTries*dlInterval+" ms");var e=new Error("Global Data Layer is not available.");
Bootstrapper.reportException(e)}};waitForGlobalDataLayer()},executeAutoLaunch:function(o,data){var boundFunction=this.executeAutoLaunch.bind(this,o,data);var debugMode=Bootstrapper.Cookies.test("enableDebug");if(window.AppMeasurement&&window.s instanceof window.AppMeasurement){if(debugMode)console.log("window.s is available after "+tries*interval+" ms");this.target=window.s;if(this.globalData.getFuncs().length)this.dataLayer=this.getData();this.target.sa(getReportSuiteId(this.dataLayer));if(top===
self||o){if(typeof Bootstrapper.nsBindingCookieExecution==="function")Bootstrapper.nsBindingCookieExecution();var savedPvData=Bootstrapper.Cookies.get(Bootstrapper.pvDataKey);if(savedPvData){savedPvData=JSON.parse(savedPvData);Bootstrapper.Cookies.del(Bootstrapper.pvDataKey);savedPvData.forEach(function(pvData){if(data.pageName!==pvData.pageName){console.log("Processing saved pageview: "+JSON.stringify(pvData,null,4));this.t.call(this,pvData)}},this.target)}var savedTlData=Bootstrapper.Cookies.get(Bootstrapper.tlDataKey);
if(savedTlData){savedTlData=JSON.parse(savedTlData);Bootstrapper.Cookies.del(Bootstrapper.tlDataKey);this.target.tl.apply(this.target,[true,"o","",savedTlData])}this.execute(data)}return}if(++tries<maxTries)setTimeout(boundFunction,interval);else{console.warn("window.s not defined!!! Aborting track call after "+tries*interval+" ms");Bootstrapper.reportException(new Error("s object not available after "+tries*interval+" ms"))}},getDataLayerProperty:function(prop){var value=this.dataLayer?this.dataLayer[prop]:
null;return value||undefinedPropPrefix+prop},getWhiteList:function(){if(!Bootstrapper.trackCallWhiteList||!Bootstrapper.trackCallWhiteList.length){Bootstrapper.reportException(new Error("Bootstrapper.trackCallWhiteList is undefined"));return null}return Bootstrapper.trackCallWhiteList}}}()},2333784,498462);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.getExtraParams=function(){return{"webview":window.easeweb&&(window.easeweb.android||window.easeweb.ios)}}},2508467,548186);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();